name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: .\scripts\_1_SetENV.ps1 && .\scripts\_3_Build.ps1
    - name: Test
      run: .\scripts\_1_SetENV.ps1 && .\scripts\_5_Tests.ps1
    - name: Test Report
      uses: dorny/test-reporter@v1
      if: success() || failure()    # run this step even if previous step failed
      with:
        name: test-results          # Name of the check run which will be created
        path: TestResults/*.trx     # Path to test results
        reporter: dotnet-trx        # Format of test results